/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.SQLException;
import bd.DAOCita;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Cita;
import model.Mascota;
import model.Veterinario;
import com.toedter.calendar.JCalendar;
import java.awt.BorderLayout;
import java.util.Date;

public class EditarCita extends javax.swing.JFrame {

    private ArrayList<Veterinario> veterinarios;
    private JCalendar calendar;

    private GestorMain gestor;
    private int idCita;
    private Cita cita;

    public EditarCita(GestorMain gestor, Cita cita, int idCita) {

        initComponents();
        this.gestor = gestor;
        this.cita = cita;
        this.idCita = idCita;

        inicializarVeterinarios();
        inicializarMascotas();

        calendar = new JCalendar();
        calendar.setMinSelectableDate(new Date());

        pnlCalendario.setLayout(new BorderLayout());
        pnlCalendario.add(calendar, BorderLayout.CENTER);
        pnlCalendario.revalidate();
        pnlCalendario.repaint();

    }

    private void inicializarVeterinarios() {
        veterinarios = new ArrayList<>();
        veterinarios.add(new Veterinario("Dr. Martín Torres", "Atención General", "+56 9 8456 3271"));
        veterinarios.add(new Veterinario("Dra. Camila Rojas", "Vacunación y Control", "+56 9 9123 4567"));
        veterinarios.add(new Veterinario("Dr. Felipe Muñoz", "Cirugía Menor", "+56 9 7765 9842"));
        veterinarios.add(new Veterinario("Dra. Valentina Pérez", "Odontología Animal", "+56 9 6523 1189"));
        veterinarios.add(new Veterinario("Dr. Ignacio Herrera", "Urgencias", "+56 9 9012 7755"));

        cmbVeterinarios.removeAllItems();
        for (Veterinario v : veterinarios) {

            cmbVeterinarios.addItem(v.toString());

        }
    }

    private void inicializarMascotas() {

        DefaultComboBoxModel<Mascota> modelo = new DefaultComboBoxModel<>();
        for (Mascota m : gestor.getListaMascotas()) {
            modelo.addElement(m);
        }
        cmbMascotas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeleccionarVeterinario = new javax.swing.JLabel();
        panelSeleccionHora = new javax.swing.JPanel();
        cmbHoras = new javax.swing.JComboBox<>();
        panelAgendar = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        lblSeleccionarDia = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        lblVolverMenu = new javax.swing.JLabel();
        lblSeleccionarHora = new javax.swing.JLabel();
        cmbMascotas = new javax.swing.JComboBox<>();
        cmbVeterinarios = new javax.swing.JComboBox<>();
        lblMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMotivo = new javax.swing.JTextArea();
        pnlCalendario = new javax.swing.JPanel();
        lblActualizarHora = new javax.swing.JLabel();
        lblSeleccionarMascota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSeleccionarVeterinario.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSeleccionarVeterinario.setText("Seleccione un veterinario disponible");

        cmbHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "12:00", "15:00", "17:00" }));
        cmbHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionHoraLayout = new javax.swing.GroupLayout(panelSeleccionHora);
        panelSeleccionHora.setLayout(panelSeleccionHoraLayout);
        panelSeleccionHoraLayout.setHorizontalGroup(
            panelSeleccionHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelSeleccionHoraLayout.setVerticalGroup(
            panelSeleccionHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionHoraLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cmbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelAgendar.setBackground(new java.awt.Color(102, 153, 255));
        panelAgendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAgendarMouseEntered(evt);
            }
        });

        lblActualizar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setText("ACTUALIZAR");
        lblActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelAgendarLayout = new javax.swing.GroupLayout(panelAgendar);
        panelAgendar.setLayout(panelAgendarLayout);
        panelAgendarLayout.setHorizontalGroup(
            panelAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelAgendarLayout.setVerticalGroup(
            panelAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        lblSeleccionarDia.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSeleccionarDia.setText("Seleccione un Dia");

        panelCancelar.setBackground(new java.awt.Color(245, 245, 220));
        panelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCancelarMouseEntered(evt);
            }
        });

        lblVolverMenu.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblVolverMenu.setForeground(new java.awt.Color(102, 153, 255));
        lblVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverMenu.setText("CANCELAR");
        lblVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        lblSeleccionarHora.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSeleccionarHora.setText("Seleccione Hora");

        cmbMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMascotasActionPerformed(evt);
            }
        });

        cmbVeterinarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMotivo.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblMotivo.setText("Escriba el motivo de su cita");

        txtAreaMotivo.setColumns(20);
        txtAreaMotivo.setRows(5);
        jScrollPane1.setViewportView(txtAreaMotivo);

        javax.swing.GroupLayout pnlCalendarioLayout = new javax.swing.GroupLayout(pnlCalendario);
        pnlCalendario.setLayout(pnlCalendarioLayout);
        pnlCalendarioLayout.setHorizontalGroup(
            pnlCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        pnlCalendarioLayout.setVerticalGroup(
            pnlCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        lblActualizarHora.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblActualizarHora.setText("Actualice su hora");

        lblSeleccionarMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSeleccionarMascota.setText("Seleccione a su mascota ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeleccionarVeterinario)
                            .addComponent(cmbVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblSeleccionarMascota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblActualizarHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeleccionarHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelSeleccionHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeleccionarDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblActualizarHora)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeleccionarMascota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeleccionarVeterinario)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeleccionarHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSeleccionHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(cmbVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMotivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblSeleccionarDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHorasActionPerformed

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked

        Mascota seleccionada = (Mascota) cmbMascotas.getSelectedItem();
        if (seleccionada == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor selecciona una mascota.");
            return;
        }

        int idMascota = seleccionada.getId();
        String veterinario = (String) cmbVeterinarios.getSelectedItem();
        Date fechaSeleccionada = calendar.getDate();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String dia = sdf.format(fechaSeleccionada);
        String hora = (String) cmbHoras.getSelectedItem();
        String motivo = txtAreaMotivo.getText();

        if (veterinario == null || dia == null || hora == null || motivo.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
            return;
        }

        try {
            DAOCita oDAOCita = new DAOCita();

            Cita citaEditada = new Cita();
            citaEditada.setIdCita(idCita);
            citaEditada.setIdMascota(idMascota);
            citaEditada.setVeterinario(veterinario);
            citaEditada.setDia(dia);
            citaEditada.setHora(hora);
            citaEditada.setMotivo(motivo);
            citaEditada.setIdCliente(Sesion.clienteActual.getId());

            oDAOCita.actualizarCita(citaEditada);

            javax.swing.JOptionPane.showMessageDialog(this, "Cita actualizada correctamente.");

            MenuGestionCitas menuCitas = new MenuGestionCitas(gestor);
            menuCitas.setVisible(true);
            this.dispose();

        } catch (SQLException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered

    }//GEN-LAST:event_lblActualizarMouseEntered

    private void panelAgendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAgendarMouseEntered

    }//GEN-LAST:event_panelAgendarMouseEntered

    private void lblVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseClicked
        MenuGestionCitas menuCitas = new MenuGestionCitas(gestor);
        menuCitas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMenuMouseClicked

    private void lblVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVolverMenuMouseEntered

    private void panelCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMouseEntered

    private void cmbMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMascotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMascotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbHoras;
    private javax.swing.JComboBox<Mascota> cmbMascotas;
    private javax.swing.JComboBox<String> cmbVeterinarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblActualizarHora;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblSeleccionarDia;
    private javax.swing.JLabel lblSeleccionarHora;
    private javax.swing.JLabel lblSeleccionarMascota;
    private javax.swing.JLabel lblSeleccionarVeterinario;
    private javax.swing.JLabel lblVolverMenu;
    private javax.swing.JPanel panelAgendar;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelSeleccionHora;
    private javax.swing.JPanel pnlCalendario;
    private javax.swing.JTextArea txtAreaMotivo;
    // End of variables declaration//GEN-END:variables
}
