/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import model.Mascota;

/**
 *
 * @author Franco
 */
public class EliminarMascota extends javax.swing.JFrame {

    private GestorMain gestor;

    public EliminarMascota(GestorMain gestor) {
        this.gestor = gestor;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblIngresarId = new javax.swing.JLabel();
        txtEntradaId = new javax.swing.JTextField();
        panelEntrar = new javax.swing.JPanel();
        lblEntrar = new javax.swing.JLabel();
        panelVolver = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();
        lblIconoBasurero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngresarId.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblIngresarId.setText("Ingrese la ID de su mascota");
        panelFondo.add(lblIngresarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, -1));

        txtEntradaId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaId.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaId.setBorder(null);
        txtEntradaId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaIdMousePressed(evt);
            }
        });
        txtEntradaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaIdActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 30));

        panelEntrar.setBackground(new java.awt.Color(102, 153, 255));
        panelEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrarMouseEntered(evt);
            }
        });

        lblEntrar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrar.setText("ENTRAR");
        lblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrarLayout.createSequentialGroup()
                .addComponent(lblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, 30));

        panelVolver.setBackground(new java.awt.Color(245, 245, 220));
        panelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVolverMouseEntered(evt);
            }
        });

        lblVolver.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblVolver.setForeground(new java.awt.Color(102, 153, 255));
        lblVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolver.setText("VOLVER");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVolverLayout.createSequentialGroup()
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 30));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Elimina los datos de tu mascota");
        panelFondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 390, 40));

        panelColor.setBackground(new java.awt.Color(102, 153, 255));
        panelColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoBasurero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/IconoBasurero.png"))); // NOI18N
        panelColor.add(lblIconoBasurero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 110));

        panelFondo.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 210, 560));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaIdMousePressed

    }//GEN-LAST:event_txtEntradaIdMousePressed

    private void txtEntradaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaIdActionPerformed

    private void lblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseClicked
        String idTexto = txtEntradaId.getText().trim();
        if (idTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una ID", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (gestor == null || gestor.getListaMascotas() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gestor no inicializado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.Mascota encontrada = null;
        for (model.Mascota m : gestor.getListaMascotas()) {
            if (idTexto.equals(String.valueOf(m.getEspecie()))) {
                encontrada = m;
                break;
            }
        }

        if (encontrada == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontro mascota con ID: " + idTexto, "No encontrado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            java.awt.EventQueue.invokeLater(() -> {
                MenuGestionMascotas menu = new MenuGestionMascotas(gestor);
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            });
            this.dispose();
            return;
        }

        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar la mascota con la ID: " + idTexto + "?",
                "Confirmar eliminacion",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            boolean eliminado = gestor.getListaMascotas().removeIf(m -> idTexto.equals(String.valueOf(m.getEspecie())));
            if (eliminado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Mascota eliminada correctamente.", "Exito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar la mascota. Intente nuevamente.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Operacion cancelada.", "Cancelado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        java.awt.EventQueue.invokeLater(() -> {
            MenuGestionMascotas menu = new MenuGestionMascotas(gestor);
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
        });
        this.dispose();
    }//GEN-LAST:event_lblEntrarMouseClicked

    private void lblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseEntered

    }//GEN-LAST:event_lblEntrarMouseEntered

    private void panelEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntrarMouseClicked

    private void panelEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseEntered

    }//GEN-LAST:event_panelEntrarMouseEntered

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        MenuGestionMascotas menu = new MenuGestionMascotas(gestor);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVolverMouseEntered

    private void panelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVolverMouseClicked

    private void panelVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVolverMouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblIconoBasurero;
    private javax.swing.JLabel lblIngresarId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JTextField txtEntradaId;
    // End of variables declaration//GEN-END:variables
}
//HOLA
