/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author Franco
 */
public class GestionMascotaMenu extends javax.swing.JFrame {

    /**
     * Creates new form RegistroMascotas
     */
    public GestionMascotaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGestionDeMascotas = new javax.swing.JLabel();
        panelEntrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        panelEntrar1 = new javax.swing.JPanel();
        lblRegistrar1 = new javax.swing.JLabel();
        panelEntrar2 = new javax.swing.JPanel();
        lblRegistrar2 = new javax.swing.JLabel();
        panelEntrar3 = new javax.swing.JPanel();
        lblRegistrar3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 190, 560));

        lblGestionDeMascotas.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblGestionDeMascotas.setText("Gestion de mascotas");
        jPanel1.add(lblGestionDeMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        panelEntrar.setBackground(new java.awt.Color(51, 51, 255));
        panelEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrarMouseEntered(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("REGISTRAR MASCOTA");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 30));

        panelEntrar1.setBackground(new java.awt.Color(51, 51, 255));
        panelEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrar1MouseEntered(evt);
            }
        });

        lblRegistrar1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblRegistrar1.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar1.setText("VER MASCOTAS");
        lblRegistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrar1Layout = new javax.swing.GroupLayout(panelEntrar1);
        panelEntrar1.setLayout(panelEntrar1Layout);
        panelEntrar1Layout.setHorizontalGroup(
            panelEntrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrar1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelEntrar1Layout.setVerticalGroup(
            panelEntrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEntrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 30));

        panelEntrar2.setBackground(new java.awt.Color(51, 51, 255));
        panelEntrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrar2MouseEntered(evt);
            }
        });

        lblRegistrar2.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblRegistrar2.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar2.setText("ACTUALIZAR DATOS");
        lblRegistrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrar2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrar2Layout = new javax.swing.GroupLayout(panelEntrar2);
        panelEntrar2.setLayout(panelEntrar2Layout);
        panelEntrar2Layout.setHorizontalGroup(
            panelEntrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrar2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblRegistrar2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntrar2Layout.setVerticalGroup(
            panelEntrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEntrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        panelEntrar3.setBackground(new java.awt.Color(51, 51, 255));
        panelEntrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrar3MouseEntered(evt);
            }
        });

        lblRegistrar3.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblRegistrar3.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar3.setText("ELIMINAR MASCOTA");
        lblRegistrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrar3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrar3Layout = new javax.swing.GroupLayout(panelEntrar3);
        panelEntrar3.setLayout(panelEntrar3Layout);
        panelEntrar3Layout.setHorizontalGroup(
            panelEntrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrar3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblRegistrar3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntrar3Layout.setVerticalGroup(
            panelEntrar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelEntrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        String usuario = txtUsuario.getText();
        String contraseña = new String(pwContra.getPassword());
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();

        //Validacion de Campos vacios
        if (usuario.isEmpty() || contraseña.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
            return;
        }

        Cliente nuevoCliente = new Cliente(usuario, contraseña, telefono, correo);

        gestor.agregarCliente(nuevoCliente);

        javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");

        LoginPrueba login = new LoginPrueba(gestor);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered

    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void panelEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseEntered

    }//GEN-LAST:event_panelEntrarMouseEntered

    private void lblRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar1MouseClicked

    private void lblRegistrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar1MouseEntered

    private void panelEntrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntrar1MouseEntered

    private void lblRegistrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar2MouseClicked

    private void lblRegistrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar2MouseEntered

    private void panelEntrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntrar2MouseEntered

    private void lblRegistrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar3MouseClicked

    private void lblRegistrar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar3MouseEntered

    private void panelEntrar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrar3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntrar3MouseEntered

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGestionDeMascotas;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistrar1;
    private javax.swing.JLabel lblRegistrar2;
    private javax.swing.JLabel lblRegistrar3;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelEntrar1;
    private javax.swing.JPanel panelEntrar2;
    private javax.swing.JPanel panelEntrar3;
    // End of variables declaration//GEN-END:variables
}
