/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Color;
import model.Cliente;

/**
 *
 * @author Franco
 */
public class LoginPrueba extends javax.swing.JFrame {

    private GestorClientes gestor;
    
    public LoginPrueba(GestorClientes gestor1) {
        this.gestor = gestor1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        txtEntradaUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblContraseña = new javax.swing.JLabel();
        pfEntradaContraseña = new javax.swing.JPasswordField();
        lblIcono = new javax.swing.JLabel();
        panelEntrar = new javax.swing.JPanel();
        lblEntrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        panelInicioSesion = new javax.swing.JPanel();
        lblRegistrar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblIniciarSesion.setText("Iniciar sesion");
        panelFondo.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        txtEntradaUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaUsuario.setText("Ingrese su nombre");
        txtEntradaUsuario.setBorder(null);
        txtEntradaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaUsuarioMousePressed(evt);
            }
        });
        txtEntradaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaUsuarioActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 320, 30));
        panelFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblContraseña.setText("Contraseña");
        panelFondo.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 110, -1));

        pfEntradaContraseña.setText("************");
        pfEntradaContraseña.setBorder(null);
        pfEntradaContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pfEntradaContraseñaMousePressed(evt);
            }
        });
        pfEntradaContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfEntradaContraseñaActionPerformed(evt);
            }
        });
        panelFondo.add(pfEntradaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 320, 30));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icono.png"))); // NOI18N
        panelFondo.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 100, 90));

        panelEntrar.setBackground(new java.awt.Color(1, 136, 123));
        panelEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrarMouseEntered(evt);
            }
        });

        lblEntrar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrar.setText("ENTRAR");
        lblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/fondoLogin.jpg"))); // NOI18N
        panelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 210, 560));

        lblUsuario1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblUsuario1.setText("Usuario");
        panelFondo.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, -1));

        panelInicioSesion.setBackground(new java.awt.Color(245, 245, 220));
        panelInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelInicioSesionMouseEntered(evt);
            }
        });

        lblRegistrar1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblRegistrar1.setForeground(new java.awt.Color(1, 136, 123));
        lblRegistrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar1.setText("REGISTRARME");
        lblRegistrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrar1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelInicioSesionLayout = new javax.swing.GroupLayout(panelInicioSesion);
        panelInicioSesion.setLayout(panelInicioSesionLayout);
        panelInicioSesionLayout.setHorizontalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelInicioSesionLayout.setVerticalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaUsuarioActionPerformed

    private void pfEntradaContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfEntradaContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfEntradaContraseñaActionPerformed

    private void lblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseEntered


    }//GEN-LAST:event_lblEntrarMouseEntered

    private void panelEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseEntered

    }//GEN-LAST:event_panelEntrarMouseEntered

    private void txtEntradaUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaUsuarioMousePressed
        if (txtEntradaUsuario.getText().equals("Ingrese su nombre")) {
            txtEntradaUsuario.setText("");
            txtEntradaUsuario.setForeground(Color.black);
        }
        if (String.valueOf(pfEntradaContraseña.getPassword()).isEmpty()) {
            pfEntradaContraseña.setText("************");
            pfEntradaContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtEntradaUsuarioMousePressed

    private void pfEntradaContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfEntradaContraseñaMousePressed
        if (String.valueOf(pfEntradaContraseña.getPassword()).equals("************")) {
            pfEntradaContraseña.setText("");
            pfEntradaContraseña.setForeground(Color.black);
        }
        if (txtEntradaUsuario.getText().isEmpty()) {
            txtEntradaUsuario.setText("Ingrese su nombre");
            txtEntradaUsuario.setForeground(Color.gray);
        }

    }//GEN-LAST:event_pfEntradaContraseñaMousePressed

    private void lblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseClicked

        
    String nombreUsuario = txtEntradaUsuario.getText();
    String password = new String(pfEntradaContraseña.getPassword());
    
    boolean encontrado = false;

    for (Cliente cliente : gestor.getListaClientes()) {
        if (cliente.getNombreUsuario().equals(nombreUsuario) && 
            cliente.getContraseña().equals(password)) {
            encontrado = true;
            break;
        }
    }

    if (encontrado) {
        javax.swing.JOptionPane.showMessageDialog(rootPane, "Has iniciado sesión correctamente");
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(rootPane, "Credenciales incorrectas");
    }


    }//GEN-LAST:event_lblEntrarMouseClicked

    private void panelEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntrarMouseClicked

    private void lblRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseClicked
        RegistrarPrueba registrarVentana = new RegistrarPrueba(gestor);
        registrarVentana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistrar1MouseClicked

    private void lblRegistrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistrar1MouseEntered

    private void panelInicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioSesionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelInicioSesionMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestorClientes gestor = new GestorClientes();
                new LoginPrueba(gestor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblRegistrar1;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JPasswordField pfEntradaContraseña;
    private javax.swing.JTextField txtEntradaUsuario;
    // End of variables declaration//GEN-END:variables
}
