/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


/**
 *
 * @author Franco
 */
public class MenuGestionMascotas extends javax.swing.JFrame {

    private GestorMain gestor;
    public MenuGestionMascotas(GestorMain gestor) {
        this.gestor = gestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoFondo = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        lblMenuPrincipalIcono = new javax.swing.JLabel();
        lblGestionDeMascotas = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        lblRegistro = new javax.swing.JLabel();
        panelVerMascota = new javax.swing.JPanel();
        lblVerMascota = new javax.swing.JLabel();
        panelActualizar = new javax.swing.JPanel();
        lblActualizar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        lblEliminar = new javax.swing.JLabel();
        pnlVolverMenu = new javax.swing.JPanel();
        lblVolverMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondoFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondoFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(102, 153, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuPrincipalIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/menu.png"))); // NOI18N
        panelFondo.add(lblMenuPrincipalIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 170));

        panelFondoFondo.add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 240, 560));

        lblGestionDeMascotas.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblGestionDeMascotas.setText("Gestion de mascotas");
        panelFondoFondo.add(lblGestionDeMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        panelRegistro.setBackground(new java.awt.Color(102, 153, 255));
        panelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistroMouseEntered(evt);
            }
        });

        lblRegistro.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistro.setText("REGISTRAR MASCOTA");
        lblRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistroMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondoFondo.add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 30));

        panelVerMascota.setBackground(new java.awt.Color(102, 153, 255));
        panelVerMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVerMascotaMouseEntered(evt);
            }
        });

        lblVerMascota.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblVerMascota.setForeground(new java.awt.Color(255, 255, 255));
        lblVerMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerMascota.setText("VER MASCOTAS");
        lblVerMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerMascotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVerMascotaMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelVerMascotaLayout = new javax.swing.GroupLayout(panelVerMascota);
        panelVerMascota.setLayout(panelVerMascotaLayout);
        panelVerMascotaLayout.setHorizontalGroup(
            panelVerMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerMascota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelVerMascotaLayout.setVerticalGroup(
            panelVerMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondoFondo.add(panelVerMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 30));

        panelActualizar.setBackground(new java.awt.Color(102, 153, 255));
        panelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelActualizarMouseEntered(evt);
            }
        });

        lblActualizar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActualizar.setText("ACTUALIZAR DATOS");
        lblActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblActualizarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarLayout = new javax.swing.GroupLayout(panelActualizar);
        panelActualizar.setLayout(panelActualizarLayout);
        panelActualizarLayout.setHorizontalGroup(
            panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelActualizarLayout.setVerticalGroup(
            panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondoFondo.add(panelActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        panelEliminar.setBackground(new java.awt.Color(102, 153, 255));
        panelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEliminarMouseEntered(evt);
            }
        });

        lblEliminar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("ELIMINAR MASCOTA");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondoFondo.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 130, 30));

        pnlVolverMenu.setBackground(new java.awt.Color(245, 245, 220));
        pnlVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlVolverMenuMouseEntered(evt);
            }
        });

        lblVolverMenu.setFont(new java.awt.Font("Roboto Condensed Light", 1, 12)); // NOI18N
        lblVolverMenu.setForeground(new java.awt.Color(102, 153, 255));
        lblVolverMenu.setText("VOLVER AL MENU");
        lblVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlVolverMenuLayout = new javax.swing.GroupLayout(pnlVolverMenu);
        pnlVolverMenu.setLayout(pnlVolverMenuLayout);
        pnlVolverMenuLayout.setHorizontalGroup(
            pnlVolverMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVolverMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        pnlVolverMenuLayout.setVerticalGroup(
            pnlVolverMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVolverMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFondoFondo.add(pnlVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        RegistroMascotas registro = new RegistroMascotas(gestor);
        registro.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void lblRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseEntered

    }//GEN-LAST:event_lblRegistroMouseEntered

    private void panelRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistroMouseEntered

    }//GEN-LAST:event_panelRegistroMouseEntered

    private void lblVerMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMascotaMouseClicked
        VerMascotas ver = new VerMascotas(gestor);
        ver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVerMascotaMouseClicked

    private void lblVerMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMascotaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVerMascotaMouseEntered

    private void panelVerMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVerMascotaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVerMascotaMouseEntered

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        ActualizarMascotas actualizarMascotas = new ActualizarMascotas(gestor);
        actualizarMascotas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblActualizarMouseEntered

    private void panelActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelActualizarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelActualizarMouseEntered

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        EliminarMascota eliminar = new EliminarMascota(gestor);
        eliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEliminarMouseEntered

    private void panelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEliminarMouseEntered

    private void lblVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseClicked
        Menu menu = new Menu(gestor);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMenuMouseClicked

    private void pnlVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVolverMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlVolverMenuMouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblGestionDeMascotas;
    private javax.swing.JLabel lblMenuPrincipalIcono;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblVerMascota;
    private javax.swing.JLabel lblVolverMenu;
    private javax.swing.JPanel panelActualizar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondoFondo;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelVerMascota;
    private javax.swing.JPanel pnlVolverMenu;
    // End of variables declaration//GEN-END:variables
}
