/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author Laboratorio
 */
public class Menu extends javax.swing.JFrame {

    private GestorMain gestor;
    
    //primer inicio
    
    public Menu() {
    initComponents();
    this.gestor = new GestorMain();
    }
    
    
    //para volver al menu y mantener el gestor
    public Menu(GestorMain gestor) {
        initComponents();
        this.gestor = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        pnlGestionarMascota = new javax.swing.JPanel();
        lblGestionarMascota = new javax.swing.JLabel();
        pnlAgendarCita = new javax.swing.JPanel();
        lblAgendarCita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 252, 253));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 560));

        panelFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/IconoMenuPrincipal.png"))); // NOI18N
        panelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 80));

        panelColor.setBackground(new java.awt.Color(1, 136, 123));
        panelColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFondo.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 220, 560));

        lblMenu.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu Principal");
        panelFondo.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 210, 40));

        pnlGestionarMascota.setBackground(new java.awt.Color(1, 136, 123));
        pnlGestionarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGestionarMascotaMouseClicked(evt);
            }
        });

        lblGestionarMascota.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblGestionarMascota.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionarMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestionarMascota.setText("GESTIONAR MASCOTAS");
        lblGestionarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionarMascotaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGestionarMascotaLayout = new javax.swing.GroupLayout(pnlGestionarMascota);
        pnlGestionarMascota.setLayout(pnlGestionarMascotaLayout);
        pnlGestionarMascotaLayout.setHorizontalGroup(
            pnlGestionarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionarMascotaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblGestionarMascota)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlGestionarMascotaLayout.setVerticalGroup(
            pnlGestionarMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionarMascotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestionarMascota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFondo.add(pnlGestionarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 180, 40));

        pnlAgendarCita.setBackground(new java.awt.Color(1, 136, 123));
        pnlAgendarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAgendarCitaMouseClicked(evt);
            }
        });

        lblAgendarCita.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        lblAgendarCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgendarCita.setText("AGENDAR CITA");
        lblAgendarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgendarCitaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAgendarCitaLayout = new javax.swing.GroupLayout(pnlAgendarCita);
        pnlAgendarCita.setLayout(pnlAgendarCitaLayout);
        pnlAgendarCitaLayout.setHorizontalGroup(
            pnlAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendarCitaLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(lblAgendarCita)
                .addGap(43, 43, 43))
        );
        pnlAgendarCitaLayout.setVerticalGroup(
            pnlAgendarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendarCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgendarCita)
                .addContainerGap())
        );

        panelFondo.add(pnlAgendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlGestionarMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGestionarMascotaMouseClicked

    }//GEN-LAST:event_pnlGestionarMascotaMouseClicked

    private void lblGestionarMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionarMascotaMouseClicked
    MenuGestionMascotas menuMascotas = new MenuGestionMascotas(gestor);
    menuMascotas.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblGestionarMascotaMouseClicked

    private void pnlAgendarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAgendarCitaMouseClicked
        MenuGestionCitas ventanaCitas = new MenuGestionCitas(gestor);
        ventanaCitas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlAgendarCitaMouseClicked

    private void lblAgendarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgendarCitaMouseClicked
        MenuGestionCitas ventanaCitas = new MenuGestionCitas(gestor);
        ventanaCitas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAgendarCitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAgendarCita;
    private javax.swing.JLabel lblGestionarMascota;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel pnlAgendarCita;
    private javax.swing.JPanel pnlGestionarMascota;
    // End of variables declaration//GEN-END:variables
}
