/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import model.Mascota;

/**
 *
 * @author Franco
 */
public class RegistroMascotas extends javax.swing.JFrame {

    private GestorMascotas gestor;
    public RegistroMascotas(GestorMascotas gestor) {
        this.gestor = gestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblIngreseDatos = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        txtEntradaNombre = new javax.swing.JTextField();
        lblIdMascota = new javax.swing.JLabel();
        txtEntradaId = new javax.swing.JTextField();
        lblRazaMascota = new javax.swing.JLabel();
        txtEntradaRaza = new javax.swing.JTextField();
        lblEdadMascota = new javax.swing.JLabel();
        txtEntradaEdad = new javax.swing.JTextField();
        lblSexoMascota = new javax.swing.JLabel();
        txtEntradaSexo = new javax.swing.JTextField();
        lblSintomasMascotas = new javax.swing.JLabel();
        txtEntradaSintomas = new javax.swing.JTextField();
        panelRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        panelVolverMenu = new javax.swing.JPanel();
        lblVolverMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondo.setForeground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngreseDatos.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblIngreseDatos.setText("Ingrese los datos");
        panelFondo.add(lblIngreseDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblNombreMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblNombreMascota.setText("Nombre de la mascota");
        panelFondo.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, -1));

        txtEntradaNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaNombre.setBorder(null);
        txtEntradaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaNombreMousePressed(evt);
            }
        });
        txtEntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaNombreActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 30));

        lblIdMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblIdMascota.setText("Asignele una ID a su mascota");
        panelFondo.add(lblIdMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        txtEntradaId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaId.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaId.setBorder(null);
        txtEntradaId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaIdMousePressed(evt);
            }
        });
        txtEntradaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaIdActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 30));

        lblRazaMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblRazaMascota.setText("Raza de la mascota");
        panelFondo.add(lblRazaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, -1));

        txtEntradaRaza.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaRaza.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaRaza.setBorder(null);
        txtEntradaRaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaRazaMousePressed(evt);
            }
        });
        txtEntradaRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaRazaActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 30));

        lblEdadMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblEdadMascota.setText("Edad de la mascota (años)");
        panelFondo.add(lblEdadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, -1));

        txtEntradaEdad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaEdad.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaEdad.setBorder(null);
        txtEntradaEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaEdadMousePressed(evt);
            }
        });
        txtEntradaEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaEdadActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 200, 30));

        lblSexoMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSexoMascota.setText("Sexo de la mascota");
        panelFondo.add(lblSexoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, -1));

        txtEntradaSexo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaSexo.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaSexo.setBorder(null);
        txtEntradaSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaSexoMousePressed(evt);
            }
        });
        txtEntradaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaSexoActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 200, 30));

        lblSintomasMascotas.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSintomasMascotas.setText("Sintomas de la mascota");
        panelFondo.add(lblSintomasMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 160, -1));

        txtEntradaSintomas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaSintomas.setForeground(new java.awt.Color(204, 204, 204));
        txtEntradaSintomas.setBorder(null);
        txtEntradaSintomas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaSintomasMousePressed(evt);
            }
        });
        txtEntradaSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaSintomasActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 200, 30));

        panelRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        panelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseEntered(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("REGISTRAR");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarLayout = new javax.swing.GroupLayout(panelRegistrar);
        panelRegistrar.setLayout(panelRegistrarLayout);
        panelRegistrarLayout.setHorizontalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelRegistrarLayout.setVerticalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 110, 30));

        panelVolverMenu.setBackground(new java.awt.Color(245, 245, 220));
        panelVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVolverMenuMouseEntered(evt);
            }
        });

        lblVolverMenu.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblVolverMenu.setForeground(new java.awt.Color(51, 102, 255));
        lblVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverMenu.setText("VOLVER AL MENU");
        lblVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelVolverMenuLayout = new javax.swing.GroupLayout(panelVolverMenu);
        panelVolverMenu.setLayout(panelVolverMenuLayout);
        panelVolverMenuLayout.setHorizontalGroup(
            panelVolverMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelVolverMenuLayout.setVerticalGroup(
            panelVolverMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 110, 30));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaNombreMousePressed

    }//GEN-LAST:event_txtEntradaNombreMousePressed

    private void txtEntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaNombreActionPerformed

    private void txtEntradaRazaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaRazaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaRazaMousePressed

    private void txtEntradaRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaRazaActionPerformed

    private void txtEntradaEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaEdadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaEdadMousePressed

    private void txtEntradaEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaEdadActionPerformed

    private void txtEntradaSexoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaSexoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaSexoMousePressed

    private void txtEntradaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaSexoActionPerformed

    private void txtEntradaSintomasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaSintomasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaSintomasMousePressed

    private void txtEntradaSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaSintomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaSintomasActionPerformed

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        String nombre = txtEntradaNombre.getText();
        String id = txtEntradaId.getText();
        String raza = txtEntradaRaza.getText();
        String edad = txtEntradaEdad.getText();
        String sexo = txtEntradaSexo.getText();
        String sintomas = txtEntradaSintomas.getText();

        if (nombre.isEmpty() || id.isEmpty() || raza.isEmpty() || edad.isEmpty() || sexo.isEmpty() || sintomas.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
            return;
        }
        Mascota nuevaMascota = new Mascota(nombre, id, raza, edad, sexo, sintomas);
        gestor.agregarMascotas(nuevaMascota);
        javax.swing.JOptionPane.showMessageDialog(this, "Mascota registrada correctamente.");
        MenuGestionMascotas menuMascotas = new MenuGestionMascotas();
        menuMascotas.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered

    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void panelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseEntered

    }//GEN-LAST:event_panelRegistrarMouseEntered

    private void lblVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseClicked
        MenuGestionMascotas menuMascotas = new MenuGestionMascotas();
        menuMascotas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMenuMouseClicked

    private void lblVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVolverMenuMouseEntered

    private void panelVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVolverMenuMouseEntered

    private void txtEntradaIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaIdMousePressed

    private void txtEntradaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaIdActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEdadMascota;
    private javax.swing.JLabel lblIdMascota;
    private javax.swing.JLabel lblIngreseDatos;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblRazaMascota;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSexoMascota;
    private javax.swing.JLabel lblSintomasMascotas;
    private javax.swing.JLabel lblVolverMenu;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPanel panelVolverMenu;
    private javax.swing.JTextField txtEntradaEdad;
    private javax.swing.JTextField txtEntradaId;
    private javax.swing.JTextField txtEntradaNombre;
    private javax.swing.JTextField txtEntradaRaza;
    private javax.swing.JTextField txtEntradaSexo;
    private javax.swing.JTextField txtEntradaSintomas;
    // End of variables declaration//GEN-END:variables
}
