/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import bd.DAOMascota;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Mascota;
import app.VerMascotas;

/**
 *
 * @author Franco
 */
public class RegistroMascotas extends javax.swing.JFrame {

    private GestorMain gestor;

    public RegistroMascotas(GestorMain gestor) {
        this.gestor = gestor;
        initComponents();
        cbSexoMascota.addItem("Macho");
        cbSexoMascota.addItem("Hembra");
        cbSexoMascota.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblIngreseDatos = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        txtEntradaNombre = new javax.swing.JTextField();
        lblEspecieMascota = new javax.swing.JLabel();
        txtEntradaEspecie = new javax.swing.JTextField();
        lblEdadMascota = new javax.swing.JLabel();
        spnEdadMascota = new javax.swing.JSpinner();
        lblSexoMascota = new javax.swing.JLabel();
        lblSintomasMascotas = new javax.swing.JLabel();
        panelRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        panelVolverMenu = new javax.swing.JPanel();
        lblVolverMenu = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();
        lblIconoRegistro = new javax.swing.JLabel();
        cbSexoMascota = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaSintomasMascotas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondo.setForeground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngreseDatos.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblIngreseDatos.setText("Ingrese los datos");
        panelFondo.add(lblIngreseDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblNombreMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblNombreMascota.setText("Nombre de la mascota");
        panelFondo.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, -1));

        txtEntradaNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaNombre.setBorder(null);
        txtEntradaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaNombreMousePressed(evt);
            }
        });
        txtEntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaNombreActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 30));

        lblEspecieMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblEspecieMascota.setText("Tipo de mascota");
        panelFondo.add(lblEspecieMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));

        txtEntradaEspecie.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaEspecie.setBorder(null);
        txtEntradaEspecie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaEspecieMousePressed(evt);
            }
        });
        txtEntradaEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaEspecieActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 30));

        lblEdadMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblEdadMascota.setText("Edad de la mascota (años)");
        panelFondo.add(lblEdadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 250, -1));
        panelFondo.add(spnEdadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, -1));

        lblSexoMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSexoMascota.setText("Sexo de la mascota");
        panelFondo.add(lblSexoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, -1));

        lblSintomasMascotas.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblSintomasMascotas.setText("Sintomas de la mascota");
        panelFondo.add(lblSintomasMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 160, -1));

        panelRegistrar.setBackground(new java.awt.Color(102, 153, 255));
        panelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistrarMouseEntered(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("REGISTRAR");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarLayout = new javax.swing.GroupLayout(panelRegistrar);
        panelRegistrar.setLayout(panelRegistrarLayout);
        panelRegistrarLayout.setHorizontalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelRegistrarLayout.setVerticalGroup(
            panelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 110, 30));

        panelVolverMenu.setBackground(new java.awt.Color(245, 245, 220));
        panelVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVolverMenuMouseEntered(evt);
            }
        });

        lblVolverMenu.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblVolverMenu.setForeground(new java.awt.Color(102, 153, 255));
        lblVolverMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverMenu.setText("VOLVER AL MENU");
        lblVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMenuMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelVolverMenuLayout = new javax.swing.GroupLayout(panelVolverMenu);
        panelVolverMenu.setLayout(panelVolverMenuLayout);
        panelVolverMenuLayout.setHorizontalGroup(
            panelVolverMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelVolverMenuLayout.setVerticalGroup(
            panelVolverMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 130, 30));

        panelColor.setBackground(new java.awt.Color(102, 153, 255));
        panelColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/IconoRegistroMascotas.png"))); // NOI18N
        panelColor.add(lblIconoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 250, 230));

        panelFondo.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 220, 640));

        cbSexoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoMascotaActionPerformed(evt);
            }
        });
        panelFondo.add(cbSexoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtaSintomasMascotas.setColumns(20);
        txtaSintomasMascotas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtaSintomasMascotas.setRows(5);
        txtaSintomasMascotas.setBorder(null);
        jScrollPane1.setViewportView(txtaSintomasMascotas);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaNombreMousePressed

    }//GEN-LAST:event_txtEntradaNombreMousePressed

    private void txtEntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaNombreActionPerformed

    private void txtEntradaEspecieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaEspecieMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaEspecieMousePressed

    private void txtEntradaEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaEspecieActionPerformed

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked

        try {
            Object seleccionado = cbSexoMascota.getSelectedItem();
            String sexo = (seleccionado == null) ? "" : (seleccionado.toString().equalsIgnoreCase("Macho") ? "M" : "H");
            if (!txtEntradaNombre.getText().isEmpty() && !txtEntradaEspecie.getText().isEmpty() && (int) spnEdadMascota.getValue() > 0 && !sexo.isEmpty() && !txtaSintomasMascotas.getText().isEmpty()) {
                DAOMascota oDao = new DAOMascota();

                Mascota oMascota = new Mascota();
                oMascota.setNombre(txtEntradaNombre.getText());
                oMascota.setEspecie(txtEntradaEspecie.getText());
                oMascota.setEdad((int) spnEdadMascota.getValue());
                oMascota.setSexo(sexo);
                oMascota.setObservaciones(txtaSintomasMascotas.getText());
                
                oMascota.setIdCliente(Sesion.clienteActual.getId());

                oDao.crearMascotas(oMascota);

                txtEntradaNombre.setText("");
                txtEntradaEspecie.setText("");
                spnEdadMascota.setValue(0);
                cbSexoMascota.setSelectedIndex(-1);
                txtaSintomasMascotas.setText("");
                txtEntradaNombre.requestFocus();
                JOptionPane.showMessageDialog(this, "Se inserto correctamente la mascota de nombre: " + oMascota.getNombre());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Porfavor complete todos los valores");
            }

        } catch (SQLException ex) {
            System.out.println("" + ex);
        }

    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered

    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void panelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistrarMouseEntered

    }//GEN-LAST:event_panelRegistrarMouseEntered

    private void lblVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseClicked
        MenuGestionMascotas menuMascotas = new MenuGestionMascotas(gestor);
        menuMascotas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMenuMouseClicked

    private void lblVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVolverMenuMouseEntered

    private void panelVolverMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMenuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVolverMenuMouseEntered

    private void cbSexoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoMascotaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSexoMascota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdadMascota;
    private javax.swing.JLabel lblEspecieMascota;
    private javax.swing.JLabel lblIconoRegistro;
    private javax.swing.JLabel lblIngreseDatos;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSexoMascota;
    private javax.swing.JLabel lblSintomasMascotas;
    private javax.swing.JLabel lblVolverMenu;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelRegistrar;
    private javax.swing.JPanel panelVolverMenu;
    private javax.swing.JSpinner spnEdadMascota;
    private javax.swing.JTextField txtEntradaEspecie;
    private javax.swing.JTextField txtEntradaNombre;
    private javax.swing.JTextArea txtaSintomasMascotas;
    // End of variables declaration//GEN-END:variables

}
