/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import model.Mascota;

/**
 *
 * @author Franco
 */
public class VerMascotas extends javax.swing.JFrame {

    private GestorMain gestor;

    public VerMascotas(GestorMain gestor) {
        this.gestor = gestor;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        txtEntradaNombre = new javax.swing.JTextField();
        panelEntrar = new javax.swing.JPanel();
        lblEntrar = new javax.swing.JLabel();
        panelVolver = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIconoLupa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(251, 252, 253));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenu.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Datos de la mascota");
        panelFondo.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 40));

        lblNombreMascota.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblNombreMascota.setText("Ingrese la ID de su mascota");
        panelFondo.add(lblNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, -1));

        txtEntradaNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEntradaNombre.setBorder(null);
        txtEntradaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEntradaNombreMousePressed(evt);
            }
        });
        txtEntradaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaNombreActionPerformed(evt);
            }
        });
        panelFondo.add(txtEntradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 30));

        panelEntrar.setBackground(new java.awt.Color(102, 153, 255));
        panelEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntrarMouseEntered(evt);
            }
        });

        lblEntrar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrar.setText("ENTRAR");
        lblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrarLayout.createSequentialGroup()
                .addComponent(lblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, 30));

        panelVolver.setBackground(new java.awt.Color(245, 245, 220));
        panelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVolverMouseEntered(evt);
            }
        });

        lblVolver.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        lblVolver.setForeground(new java.awt.Color(102, 153, 255));
        lblVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolver.setText("VOLVER");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelVolverLayout = new javax.swing.GroupLayout(panelVolver);
        panelVolver.setLayout(panelVolverLayout);
        panelVolverLayout.setHorizontalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVolverLayout.createSequentialGroup()
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelVolverLayout.setVerticalGroup(
            panelVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelFondo.add(panelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 80, 30));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/iconoLupa.png"))); // NOI18N
        jPanel2.add(lblIconoLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 210));

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 560));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntradaNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEntradaNombreMousePressed

    }//GEN-LAST:event_txtEntradaNombreMousePressed

    private void txtEntradaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaNombreActionPerformed

    private void lblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseClicked
        String idBuscada = txtEntradaNombre.getText().trim();
        if (idBuscada.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una ID", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        boolean encontrado = false;
        if (gestor != null && gestor.getListaMascotas() != null) {
            for (model.Mascota m : gestor.getListaMascotas()) {
                String idMascota = m.getEspecie(); 
                if (idBuscada.equals(idMascota)) {
                    encontrado = true;
                    String msg = String.format(
                            "ID: %s%nNombre: %s%nTipo: %s%nEdad: %s%nSexo: %s%nObservaciones: %s",
                            idMascota,
                            safe(m.getNombre()),
                            safe(m.getRaza()),
                            safe(m.getEdad()),
                            safe(m.getSexo()),
                            safe(m.getObservaciones())
                    );
                    javax.swing.JOptionPane.showMessageDialog(this, msg, "Datos de la mascota", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
        }

        if (!encontrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró mascota con ID: " + idBuscada, "No encontrado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private String safe(String s) {
        return s == null ? "" : s;

    }//GEN-LAST:event_lblEntrarMouseClicked

    private void lblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseEntered

    }//GEN-LAST:event_lblEntrarMouseEntered

    private void panelEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntrarMouseClicked

    private void panelEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntrarMouseEntered

    }//GEN-LAST:event_panelEntrarMouseEntered

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        MenuGestionMascotas menu = new MenuGestionMascotas(gestor);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVolverMouseEntered

    private void panelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVolverMouseClicked

    private void panelVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVolverMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelVolverMouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblIconoLupa;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JTextField txtEntradaNombre;
    // End of variables declaration//GEN-END:variables
}

